### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by coreeey** [JiYuanFeng/AMOS#1]
Hello, where is the code for reproducing the result?

**Comment by JiYuanFeng** [comment]
HI, since the reproduction requires gt annotation of the validation set, and it is currently being used as an online validation set for the AMOS22 competition (https://amos22.grand-challenge.org/), the validation set will be fully published after the first phase, when we will publish the code, please stay tuned.

**Comment by JiYuanFeng** [comment]
Hi, so sorry to keep you waiting, the code is available in  https://github.com/JiYuanFeng/AMOS/blob/code
